server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: front
          uri: http://localhost:8082
          predicates:
            - Path=/orders/**, /payments/**, 
        - id: store
          uri: http://localhost:8083
          predicates:
            - Path=/storeOrders/**, 
        - id: delivery
          uri: http://localhost:8085
          predicates:
            - Path=/dekeveries/**, 
        - id: summary
          uri: http://localhost:8088
          predicates:
            - Path=/alertLogs/**, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: front
          uri: http://front:8080
          predicates:
            - Path=/orders/**, /payments/**, 
        - id: store
          uri: http://store:8080
          predicates:
            - Path=/storeOrders/**, 
        - id: delivery
          uri: http://delivery:8080
          predicates:
            - Path=/dekeveries/**, 
        - id: summary
          uri: http://summary:8080
          predicates:
            - Path=/alertLogs/**, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
